services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        environment:
            - REDIS_PASSWORD=redispassword
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgrespassword
            - POSTGRES_DB=smoothiedb
        volumes:
            - postgres-data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin  
        ports:
            - "8080:80"
        depends_on:
            - postgres
        volumes:
            - pgadmin-data:/var/lib/pgadmin
volumes:
    postgres-data:
        driver: local
    pgadmin-data:
        driver: local